Experiment.StartNewSection('Analysis');

c2stErrorMetricsPerObserverPerAppearance = FileIOUtils.LoadMatFile(...
    fullfile(ExperimentManager.GetPathToExperimentAssetResultsDirectory('AYS-105-002-002'), '01 Analysis', 'Error Metrics and Predicted Labels.mat'),...
    'c2stErrorMetricsPerObserverPerAppearance');

% variables: 5 appearances
% groups: AUC 0.632+, AUC, MCR, FPR, FNR

 m2dDataPerGroupPerVariable = zeros(5,5);
 m2dErrorBarSizePerGroupPerVariable = zeros(5,5);
 
 for dAppearanceIndex=1:5
      m2dDataPerGroupPerVariable(1,dAppearanceIndex) = c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.dAUC_0Point632Plus;
      m2dDataPerGroupPerVariable(2,dAppearanceIndex) = c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdAUCAndCI(1);
      m2dDataPerGroupPerVariable(3,dAppearanceIndex) = c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdMCRAndCI(1);
      m2dDataPerGroupPerVariable(4,dAppearanceIndex) = c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFPRAndCI(1);
      m2dDataPerGroupPerVariable(5,dAppearanceIndex) = c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFNRAndCI(1);
     
     m2dErrorBarSizePerGroupPerVariable(2,dAppearanceIndex) = mean([c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdAUCAndCI(2) - c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdAUCAndCI(1) c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdAUCAndCI(1) - c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdAUCAndCI(3)]);
     m2dErrorBarSizePerGroupPerVariable(3,dAppearanceIndex) = mean([c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdMCRAndCI(2) - c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdMCRAndCI(1) c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdMCRAndCI(1) - c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdMCRAndCI(3)]);
     m2dErrorBarSizePerGroupPerVariable(4,dAppearanceIndex) = mean([c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFPRAndCI(2) - c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFPRAndCI(1) c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFPRAndCI(1) - c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFPRAndCI(3)]);
     m2dErrorBarSizePerGroupPerVariable(5,dAppearanceIndex) = mean([c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFNRAndCI(2) - c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFNRAndCI(1) c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFNRAndCI(1) - c2stErrorMetricsPerObserverPerAppearance{1,dAppearanceIndex}.vdFNRAndCI(3)]);
 end
 
 vsLabelPerGroup = ["AUC_{0.632+}" "AUC" "MCR %" "FNR %" "FPR %"];
 
 [hFig, hLegendFig, hAxes] = CreateBarGraph(...
     m2dDataPerGroupPerVariable, vsLabelPerGroup,...
     'ErrorBarSizePerGroupPerVariable', m2dErrorBarSizePerGroupPerVariable,...
    'FontSize', 8, 'FontName', 'Arial',...
    'GroupSpacing', 0.1, 'VariableSpacing', 0.015,...
    'TexturePerVariable', ["Line45" "Solid" "Line45" "Solid" "Cross45"],...
    'BarColourPerVariable', {[1 1 1], [1 1 1], [0 0 0], [0 0 0], [1 1 1]},...
    'TextureColourPerVariable', {[0 0 0],[],[1 1 1],[],[0 0 0]},...
    'LegendVariableNames', ["Homogeneous" "Heterogeneous" "Cystic (Simple)" "Cystic (Complex)" "Necrosis"],...
    'FigureSize', [17.5, 7.5], 'FigureSizeUnits', 'centimeter',...
    'FillFigure', true,...
    'YLabel', 'Error Metric Value',...
    'YTicks', 0:0.1:1, 'YLim', [0 1],...
    'TextureLineWidth', 2, 'TextureLineSpacing', 5.8,...
    'LatexOn', false,...
    'TopErrorBarOnly', true,...
    'GroupLabelOffset', 0.015, 'GroupLabelVerticalAlignment', 'top');

hAxes.YAxis.MinorTickValues = 0.05:0.1:0.95;
hAxes.YMinorGrid = 'on';

savefig(hFig, fullfile(Experiment.GetResultsDirectory(), 'Error Metric Bar Chart.fig'));
saveas(hFig, fullfile(Experiment.GetResultsDirectory(), 'Error Metric Bar Chart.svg'));

delete(hFig);
delete(hLegendFig);

 [hFig, hLegendFig, hAxes] = CreateBarGraph(...
     m2dDataPerGroupPerVariable, vsLabelPerGroup,...
     'ErrorBarSizePerGroupPerVariable', m2dErrorBarSizePerGroupPerVariable,...
    'FontSize', 8, 'FontName', 'Arial',...
    'GroupSpacing', 0.1, 'VariableSpacing', 0.015,...
    'TexturePerVariable', ["Line45" "Solid" "Line45" "Solid" "Cross45"],...
    'BarColourPerVariable', {[1 1 1], [1 1 1], [0 0 0], [0 0 0], [1 1 1]},...
    'TextureColourPerVariable', {[0 0 0],[],[1 1 1],[],[0 0 0]},...
    'LegendVariableNames', ["Homogeneous" "Heterogeneous" "Cystic (Simple)" "Cystic (Complex)" "Necrosis"],...
    'FigureSize', [17.5, 9], 'FigureSizeUnits', 'centimeter',...
    'FillFigure', true,...
    'YLabel', 'Error Metric Value',...
    'YTicks', 0:0.1:1, 'YLim', [0 1],...
    'TextureLineWidth', 1.25, 'TextureLineSpacing', 3.5,...
    'LatexOn', false,...
    'TopErrorBarOnly', true,...
    'GroupLabelOffset', 0.015, 'GroupLabelVerticalAlignment', 'top');

savefig(hLegendFig, fullfile(Experiment.GetResultsDirectory(), 'Error Metric Bar Chart Legend.fig'));
saveas(hLegendFig, fullfile(Experiment.GetResultsDirectory(), 'Error Metric Bar Chart Legend.svg'));

delete(hFig);
delete(hLegendFig);